### ISSUE TITLE
Invalid Hex Characters when creating Receive Block

### ISSUE THREAD

**Issue by albertlt** [miguel1117/Nano.Net#10]
Hello. First of all, great library, thank you. I tried to receive 0.001 XNO but the Blok.CreateReceiveBlock() throwed an "invalid hex characters" error.

await rpcClient.UpdateAccountAsync(account);

var receiveBlock = Block.CreateReceiveBlock(account, "PENDING_BLOCK_HASH", Amount.FromNano("0.001"), "POW_NONCE");

await rpcClient.ProcessAsync(receiveBlock);

**Comment by albertlt** [comment]
Also tried the send block example and I got the following error:

Nano.Net.RpcException: 'RPC call returned error. Message: Block is invalid'

I followed the code from example changing only: Amount.FromRaw("1") to Amount.FromNano("0.001")

var receiveBlock = Block.CreateReceiveBlock(account, "PENDING_BLOCK_HASH", Amount.FromNano("0.001"), "POW_NONCE");

**Comment by miguel1117** [comment]
Hey, I'm not able to reproduce the issue you're having.
I'm assuming you're replacing "PENDING_BLOCK_HASH" and "POW_NONCE" with the correct values, right? If you are, please send more details about the error.

**Comment by albertlt** [comment]
So here is the code in vb.net for receive:

Dim acc As Account = Account.FromPrivateKey(txtSeeds.Text)
Dim rpc As New RpcClient(NODE_ADDR)

Await rpc.UpdateAccountAsync(acc)

Dim receiveBlock As Block = Block.CreateReceiveBlock(acc, "PENDING_BLOCK_HASH", Amount.FromNano("0.001"), "POW_NONCE")

Await rpc.ProcessAsync(receiveBlock)

**Comment by albertlt** [comment]
And here is for send:

Dim acc As Account = Account.FromPrivateKey(txtSeeds.Text)
Dim rpc As New RpcClient(NODE_ADDR)

Await rpc.UpdateAccountAsync(acc)

 'Creates a block and automatically sign it. The PoW nonce has to be obtained externally.
 Dim sendBlock As Block = Block.CreateSendBlock(acc, txtWallet.Text, Amount.FromNano("0.001"), "POW_NONCE")

 'Publish the block to the network.
  Await rpc.ProcessAsync(sendBlock)

**Comment by albertlt** [comment]
Btw, where can i find list of available commands and explanations for "POW_NONCE" and "PENDING_BLOCK_HASH" ?

**Comment by miguel1117** [comment]
"POW_NONCE" and "PENDING_BLOCK_HASH" are simply placeholders for their values.
You need to replace PENDING_BLOCK_HASH with the hash of the block you're trying to receive and POW_NONCE with the proof of work nonce you've generated for this block.

**Comment by albertlt** [comment]
Oh I see. Now everything make sense. However, how do I obtain the PENDING_BLOCK_HASH for pending transaction  and also the POW_NONCE? I read the comment about getting the POW_NONCE externally, how to do that?

**Comment by miguel1117** [comment]
You can create an RpcClient object and use its PendingBlocksAsync method to fetch pending blocks for an account. You can find the block hash in the hash property of a ReceivableBlock object.

**Comment by miguel1117** [comment]
> I read the comment about getting the POW_NONCE externally, how to do that?

About this part, there are multiple ways to do this, but the easiest one would be running [nano-work-server](https://github.com/nanocurrency/nano-work-server) (you'll need a GPU or a decent CPU), create a new RpcClient object with its address and calling the WorkGenerateAsync method. You could also run a node or use a 3rd party service.
For more information about work generation you should check https://docs.nano.org/integration-guides/work-generation/ and if you need further help with nano itself I recommend you join the official Discord server.

**Comment by albertlt** [comment]
Great, thank you for your explanation !

**Comment by albertlt** [comment]
Btw, I am using public node api that support 'work_generate'. I can get the pending hash and I tried to get the nonce with:

workResponse = Await rpc.WorkGenerateAsync(rcvBlock.Hash)

Then I call:
Dim receiveBlock As Block = Block.CreateReceiveBlock(acc, rcvBlock.Hash, Amount.FromRaw(rcvBlock.Amount), workResponse.Work)

Await rpc.ProcessAsync(receiveBlock)

but I got:
'RPC call returned error. Message: Block work is less than threshold'
 
Is it correct to put workResponse.Work into "NONCE_POW" field?

**Comment by albertlt** [comment]
I tried the following difficulties: "fffffe0000000000", "ffffffc000000000" and "fffffff800000000", all not working. I tried to google the error message but still can't get any solution. Can you please help? Below is full receive code:

        Dim acc As Account = Account.FromPrivateKey(txtSeeds.Text)
        Dim rpc As New RpcClient(NODE_ADDR) 'https://mynano.ninja/api/node

        'Check for pending blocks
        Dim response As ReceivableBlocksResponse
        Dim rcvBlock As ReceivableBlock
        Dim workResponse As WorkGenerateResponse

        Await rpc.UpdateAccountAsync(acc)

        response = Await rpc.PendingBlocksAsync(acc.Address)

        If response.PendingBlocks.Count > 0 Then
            For Each kvp As KeyValuePair(Of String, ReceivableBlock) In response.PendingBlocks
                rcvBlock = kvp.Value

                workResponse = Await rpc.WorkGenerateAsync(rcvBlock.Hash)

                Dim receiveBlock As Block = Block.CreateReceiveBlock(acc, rcvBlock.Hash, Amount.FromRaw(rcvBlock.Amount), workResponse.Work)

                Await rpc.ProcessAsync(receiveBlock)

            Next
        End If

**Comment by miguel1117** [comment]
Sorry, I've only seen this comment now, and I think others have already helped you in the nano server. 
Also, this is not the right place to get support for issues that are related to the protocol itself. You should ask about these things in the nano server after looking through the docs.

**Comment by albertlt** [comment]
it's ok. I got it all resolved. thanks and great library ! :)
