### ISSUE TITLE
How to input Natrium's seed phrase

### ISSUE THREAD

**Issue by albertlt** [miguel1117/Nano.Net#11]
Hi. This is actually not an issue. May I know for what value should I put for index if I want to import seed from Natrium wallet? Also for the seed variable, is the format 24 words separated by space? eg: "police missing bribe ..."

Account.FromSeed(string seed, uint index, string prefix = "nano")

**Comment by miguel1117** [comment]
The library does not support mnemonics yet. As for hex seeds, you can import them with Account.FromSeed(). The index is the index of the account you want. If you want the first account, then the index should be 0, 1 for the second, etc.

**Comment by albertlt** [comment]
Great thank you !
